Repository Gaongil/Gaongil, pull requests merged in 2022-11, with the labels that each got.

#29 [FEAT] 설정뷰의 개인정보처리방침 삭제
  Gaongil/Controllers/Setting/SettingsViewController.swift
Labels: feat, 👨‍⚖️ oz, ⚙️ Settings

#31 [FEAT] 기존 사용자의 경우 TodayLawViewController로 바로 이동할 수 있도록 구현
  Gaongil/Controllers/SelectCategoryViewController.swift
  Gaongil/SceneDelegate.swift
Labels: feat, 👩‍⚖️ lena

#33 [FEAT] API 에서 받은 데이터를 CollectionView 에 로딩 및 오타 수정
  Gaongil/Controllers/DetailViewController.swift
  Gaongil/Controllers/SelectCategoryViewController.swift
  Gaongil/Controllers/TodayLawViewController.swift
  Gaongil/Manager/CoreDataManager.swift
  Gaongil/Manager/ResponseManager.swift
  Gaongil/Model/CommitteeName.swift
  Gaongil/Views/CommitteeListView.swift
Labels: 👨‍⚖️ Niro, feat, UI

#35 [FEAT] 신호등 기능 구현
  Gaongil.xcodeproj/project.pbxproj
  Gaongil/Controllers/MainTabBarController.swift
  Gaongil/Controllers/TodayLawViewController.swift
  Gaongil/Views/CircularProgressBarView.swift
  Gaongil/Views/TodayLawCollectionViewCell.swift
Labels: feat, 👩‍⚖️ lena

#37 [FEAT] 웹페이지 이동 기능 구현
  Gaongil/Controllers/DetailViewController.swift
  Gaongil/Controllers/MainTabBarController.swift
  Gaongil/Controllers/TodayLawViewController.swift
  Gaongil/Views/CustomView.swift
Labels: 👩‍⚖️ lena

#40 [FEAT] FavoriteDetailView에서 해당 링크 연결 추가 #39
  Gaongil/Controllers/FavoriteDetailViewController.swift
Labels: 👨‍⚖️ Niro, feat, UI

#42 [HOTFIX] SettingView 버그 및 navigationBar title 사이즈 오류 수정
  Gaongil/Controllers/DetailViewController.swift
  Gaongil/Controllers/SelectCategoryViewController.swift
  Gaongil/Controllers/Setting/DeveloperPageViewController.swift
  Gaongil/Controllers/Setting/SettingsViewController.swift
  Gaongil/Controllers/TodayLawViewController.swift
Labels: bug, 👩‍⚖️ lena
